apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: HTTP-testing-for-get-mock-proxy-local-5001
  title: Http testing for get New API proxy local 5001
  description: Testing get functionality with get proxy local 5001
spec:
  owner: roadie
  type: service

  parameters:
    - title: Fill in some params for request
      properties:
        repoUrl:
          title: RepoUrl
          type: string
          description: Path lưu trữ file backstage
          ui:autofocus: true
          ui:options:
            rows: 15
        name:
          title: Name
          type: string
          description: Name
          ui:autofocus: true
          ui:options:
            rows: 5
        age:
          title: Age
          type: string
          description: Age
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: backstage_request_with_input
      name: backstage request
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/local-mock/update-user'
        headers:
          content-type: 'application/json'
        body:
          name: 'test'
          bar: 'foo' 
          reqBody:  ${{parameters}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'some/path/catalog-info.yaml'

  output:
    getResponse: '{{ steps.backstage_request.output.body }}'
    getCode: '{{ steps.backstage_request.output.code }}'
    getHeaders: '{{ steps.backstage_request.output.headers }}'