apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: HTTP-testing-for-get-mock-proxy-local-5000
  title: Http testing for get New API proxy local 5000
  description: Testing get functionality with get proxy local 5000
spec:
  owner: roadie
  type: service

  parameters:
    - title: Fill in some params for request
      properties:
        httpGetPath:
          title: Get Path
          type: string
          description: The path you want to get on your backstage instance
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: backstage_request
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/local-mock/users'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: backstage_request
      name: backstage request
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/local-mock/users'
        headers:
          content-type: 'application/json'
      body:
        name: 'test'
        bar: 'foo'   
         
  output:
    getResponse: '{{ steps.backstage_request.output.body }}'
    getCode: '{{ steps.backstage_request.output.code }}'
    getHeaders: '{{ steps.backstage_request.output.headers }}'