apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: majestic-monolith
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
